### ISSUE TITLE
Initialization script?

### ISSUE THREAD

**Issue by janoszen** [Supervisor/supervisor#1005]
Supervisord is rapidly becoming the tool of choice for running services in Docker containers. However, many Docker containers need some sort of initialization to configure the software within from environment variables.

Therefore, please consider adding a feature that allows for executing a script upon startup.

**Comment by mnaberez** [comment]
Instead of running the command `supervisord`, run the command `bash start.sh`:

```
#!/bin/sh

... do work here ...

exec supervisord -c supervisord.conf
```

The shell script will do its work and then the `exec` will cause its process to be replaced by `supervisord`.  The end result is the same as if `supervisord` was run directly.

The example above is more powerful than if a special "startup script" option was added to `supervisord`.  The example above can `export` environment variables and those variables will appear in `supervisord`'s environment.  A subprocess run under `supervisord` can't do this.  The variant of the example above could also choose not to start `supervisord` if it detects something is wrong.
