### ISSUE TITLE
No module named supervisor.confecho

### ISSUE THREAD

**Issue by SaurabhJ86** [Supervisor/supervisor#1022]
I am getting this error when I am trying to run the following command "echo_supervisord_conf".
Going through the steps in the guide I installed supervisor using the command "pip install supervisor" and once installed successfully when I run the command "echo_supervisord_conf", I am getting the error "No module named supervisor.confecho". 
This is working just fine on my local MacOS, I am only getting this error from my hosting service provider which uses CentOS.

Please let me know if I need to add anything else here.

Following is the content of the file echo_supervisord_conf

#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from supervisor.confecho import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

**Comment by mnaberez** [comment]
Here is the result of installing the `supervisor` package via `pip` in a fresh Python 2 environment:

```
$ virtualenv --no-site-packages venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/username/venv/bin/python2
Also creating executable in /home/username/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

$ venv/bin/pip install supervisor
Collecting supervisor
  Downloading supervisor-3.3.3.tar.gz (418kB)
    100% |████████████████████████████████| 419kB 3.1MB/s 
Collecting meld3>=0.6.5 (from supervisor)
  Downloading meld3-1.0.2-py2.py3-none-any.whl
Building wheels for collected packages: supervisor
  Running setup.py bdist_wheel for supervisor ... done
  Stored in directory: /home/username/.cache/pip/wheels/87/bb/89/3a9d0687626bfaf53832271a4846cca5a895648a4a3d44d1fb
Successfully built supervisor
Installing collected packages: meld3, supervisor
Successfully installed meld3-1.0.2 supervisor-3.3.3

$ venv/bin/echo_supervisord_conf 
; Sample supervisor config file.
;
; For more information on the config file, please see:
; http://supervisord.org/configuration.html
;
; Notes:
;  - Shell expansion ("~" or "$HOME") is not supported.  Environment
;    variables can be expanded using this syntax: "%(ENV_HOME)s".
;  - Quotes around values are not supported, except in the case of
;    the environment= options as shown below.
;  - Comments must have a leading space: "a=b ;comment" not "a=b;comment".
;  - Command will be truncated if it looks like a config file comment, e.g.
;    "command=bash -c 'foo ; bar'" will truncate to "command=bash -c 'foo ".

[unix_http_server]
file=/tmp/supervisor.sock   ; the path to the socket file
...
```

The `echo_supervisord_conf` command does work above, so it doesn't look like there is any issue with the package.  We don't have any platform-specific code that we could change to affect this issue (e.g. CentOS or MacOS mentioned above) because the installation of console scripts is handled by `setuptools`.  I suspect something is wrong with the particular Python environment you are installing into, but I don't know what and I'm not able to help troubleshoot it.  You might try asking on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).
