### ISSUE TITLE
Supervisor does not detect any secondary group a user belongs to

### ISSUE THREAD

**Issue by wbytebier** [Supervisor/supervisor#1030]
In our setup, we are running sssd, and none of the users used with Supervisor have entries in /etc/passwd or /etc/group.
In this case Supervisor only detects the primary group, and none of the secondary groups.

**Comment by mnaberez** [comment]
`supervisord` doesn't dig around in any of those files itself.  [It calls](https://github.com/Supervisor/supervisor/blob/3.3.3/supervisor/options.py#L1261-L1306) Python's [`grp.getgrall()`](https://docs.python.org/2/library/grp.html#grp.getgrall) to get a list of groups and its members, finds all groups the user is a member of, then calls [`os.setgroups()`](https://docs.python.org/2/library/os.html#os.setgroups).  If the groups can't be found/set using these mechanisms, then `supervisord` can't be used.

**Comment by lfrancke** [comment]
For anyone else stumbling across this: Python's `getgrall()` calls `getgrent()` under the hood which does not necessarily list groups from SSSD. You need to enable enumeration in SSSD for that to work (which also is not ideal due to its performance impact). RedHat has a Knowledge Base article for this: https://access.redhat.com/solutions/657713

**Comment by gerases** [comment]
@lfrancke , this helped solve a long standing bug. Thank you!
