### ISSUE TITLE
Documentation should state which sections are required

### ISSUE THREAD

**Issue by basickarl** [Supervisor/supervisor#1052]
http://supervisord.org/configuration.html

Currently, I have no idea which sections are required for the configuration file to be valid. This should be stated.

An example would be this:
```
admin@karl:/$ supervisorctl
Error: .ini file does not include supervisorctl section
For help, use /usr/local/bin/supervisorctl -h
```

Since it's not stated, it's hard to know. Would be great if this could be stated like the section fields do.

**Comment by mnaberez** [comment]
When the config file is read by `supervisord`, only the `[supervisord]` section is required.  All other sections are optional, although `supervisord` doesn't do much without them.  When the config file is read by `supervisorctl`, only the `[supervisorctl]` section is required.  I'm not sure it's worth adding special notes to the documentation about this since neither program will accept a config file without the required sections, and these are the only ones.  I'll merge a PR if you want to add it.

**Comment by ExperimentalHypothesis** [comment]
all the time i get either 
Error: .ini file does not include supervisord section
or 
Error: .ini file does not include supervisorctl section
or 
http://localhost:9001 refused connection

my config file looks like this
`
[program:flaskapp]
directory=/home/online-radio
command=/home/online-radio/venv/bin/gunicorn -w 3 run:app
user=root
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/flaskapp/flaskapp.err.log
stdout_logfile=/var/log/flaskapp/flaskapp.out.log

[supervisorctl]

[supervisord]
`
supervisord -c /etc/supervisor/conf.d/flaskapp.conf
supervisorctl -c /etc/supervisor/conf.d/flaskapp.conf

it is pretty annoying. i have spent already more than a day to fix it, still not working.. 

what am i doing wrong?
