### ISSUE TITLE
Slow supervisor shutdown

### ISSUE THREAD

**Issue by henkesde92** [Supervisor/supervisor#1155]
We use the supervisor to start uwsgi processes to host the backend of our applications. We could observe that superisor shutdown is much slower than stopping all the different processes using stopProcess.

"supervisor stop" is our stopProcess Wrapper:
![image](https://user-images.githubusercontent.com/26405713/46594697-fc535f80-cad4-11e8-965d-b3097fbbfcf5.png)

"supervisor stop_sv" is our shutdown Wrapper:
![image](https://user-images.githubusercontent.com/26405713/46594717-12612000-cad5-11e8-818b-39a2c25729db.png)

Even 24 secs appear pretty long because killing a single uWSGI process only takes about 2.5 secs:
![image](https://user-images.githubusercontent.com/26405713/46594873-e2fee300-cad5-11e8-91a9-d1a15a06212b.png)

This is related to Seldaek's comment in #723. Kill signal should probably be send in parallel to all processes and not one by one.  I also read #326 but it doesn't seem to work in our setup.

If you need additional information, don't hesitate to contact me.

Edit: We use python 3.

**Comment by mnaberez** [comment]
There is not enough information in this report to allow it to be investigated.  We don't know what these "wrapper" scripts are or what they are doing, how you have configured `supervisord` in the `supervisord.conf` file(s), or what `supervisord` is logging when it is being "too slow".  

To allow a developer to troubleshoot it, there needs to be a way to reproduce it that is not dependent on your particular infrastructure (since we don't have insight into any of that).  For example, give steps that would allow us to reproduce by providing a complete `supervisord.conf` file that someone can run, specific `supervisorctl` commands to issue, the results that should be expected, and why you think those results are a problem.
