### ISSUE TITLE
installing older version of supervisor giving error

### ISSUE THREAD

**Issue by SajEng** [Supervisor/supervisor#1204]
pip install supervisor==2.1

Could not find a version that satisfies the requirement 2.1 (from versions: )
No matching distribution found for 2.1

**Comment by mnaberez** [comment]
> pip install supervisor==2.1

This is an ancient version of Supervisor that was released in 2007.  It is no longer supported and is not recommended for use.  Please upgrade to a newer version.

Supervisor packages were uploaded to [PyPI](https://pypi.org/project/supervisor/) since version 3.0a7, released in 2009.  All releases since 3.0a7 should be downloadable from PyPI.  Packages for versions before 3.0a7 used to be hosted on `plope.com` or `dist.supervisord.org`, but both of those servers have been down for years.  The [Wayback Machine](https://archive.org) may have backups of those sites, or you may be able to build the ancient packages from this git repository.  The Supervisor project can't provide any support for finding or building packages for versions of Supervisor that are over a decade old, sorry.
