### ISSUE TITLE
Error: Can't drop privilege as nonroot user

### ISSUE THREAD

**Issue by axot** [Supervisor/supervisor#1218]
After upgrading 3.3.1 to 3.3.4, supervisor gives up startup with `Error: Can't drop privilege as nonroot user`, in the previous version, it showed `CRIT Can't drop privilege as nonroot user` then keep running. 

We want to use the same config file in both root and non-root environment, any advice?

**Comment by mnaberez** [comment]
What are the contents of your config file?  There are two places that `user=` can be set (in the `[supervisord]` section and in any `[program:x]` section).  We need to know the configuration so we can look at the relevant code and changes between versions.  I'm not aware of any changes related to user switching between 3.3.1 and 3.3.4 ([changelog](https://github.com/Supervisor/supervisor/blob/3.3.5/CHANGES.txt)).

**Comment by axot** [comment]
Hi @mnaberez , here is the config which we are testing unber 3.3.4 and 3.3.1.

```
[unix_http_server]
file=/run/supervisord.sock   ; (the path to the socket file)
;chmod=0700                  ; socked file mode (default 0700)
;chown=nobody:nogroup        ; socket file uid:gid owner
;username=user               ; (default is no username (open server))
;password=123                ; (default is no password (open server))

[supervisord]
logfile=/var/log/supervisord.log ; (main log file;default $CWD/supervisord.log)
;logfile_maxbytes=50MB       ; (max main logfile bytes b4 rotation;default 50MB)
;logfile_backups=10          ; (num of main logfile rotation backups;default 10)
loglevel=info                ; (log level;default info; others: debug,warn,trace)
pidfile=/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
;nodaemon=false              ; (start in foreground if true;default false)
minfds=4096                  ; (min. avail startup file descriptors;default 1024)
minprocs=1024                ; (min. avail process descriptors;default 200)
;umask=022                   ; (process file creation umask;default 022)
user=root                    ; (default is current user, required if root)
;identifier=supervisor       ; (supervisord identifier, default is 'supervisor')
;directory=/tmp              ; (default is not to cd during start)
;nocleanup=true              ; (don't clean up tempfiles at start;default false)
childlogdir=/var/log         ; ('AUTO' child log dir, default $TEMP)
;environment=KEY=value       ; (key value pairs to add to environment)
;strip_ansi=false            ; (strip ansi escape codes in logs; def. false)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock ; use a unix:// URL  for a unix socket
;serverurl=http://127.0.0.1:9001 ; use an http:// url to specify an inet socket
;username=chris              ; should be same as http_username if set
;password=123                ; should be same as http_password if set
;prompt=mysupervisor         ; cmd line prompt (default "supervisor")
;history_file=~/.sc_history  ; use readline history if available

; The below sample program section shows all possible program subsection values,
; create one or more 'real' program: sections to be able to control them under
; supervisor.

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize --fpm-config /usr/local/etc/php-fpm.conf
autostart=true
autorestart=false
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=false
priority=10
stdout_events_enabled=true
stderr_events_enabled=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:startup]
command=startup
autostart=true
autorestart=false
startretries=0
priority=15
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
```

**Comment by mnaberez** [comment]
This was indeed changed (in version 3.3.4).  I have added the missing changelog entry in a2adcb3a957d5ed5b9844b3010a49a2338438da2.

**Comment by mnaberez** [comment]
The config file above can be distilled to:

```
[supervisord]
user=root
```

This is fine when `supervisord` is run as root but you're also asking to use `user=root` when run as non-root.  However, a non-root user can't switch to root.  

In versions before 3.3.4, `supervisord` would log a message at the `critical` level but would continue running (and spawning subprocesses) if it could not `setuid()` to the specified user.  

In 3.3.4, the behavior was changed to simply exit immediately anytime you configure `supervisord` to switch to a user but it can't fulfill what you configured.  It was changed for consistency.  Processing the rest of the config file tries to fail fast whenever it can't fulfill what has been configured.  The intention is that if `supervisord` successfully starts, it has fulfilled what has been configured.

> We want to use the same config file in both root and non-root environment, any advice?

You can remove `user=root` entirely, which will allow `supervisord` to start as root or non-root.  When run as root, this has the side effect of printing a warning message to the log, since we recommend having a `user=` when run as root.  Assuming the environment that `supervisord` is started in contains the variable `USER` and it is set to the current user, you should be able to use `user=%(ENV_USER)s` to run as either user.

**Comment by axot** [comment]
Hello @mnaberez, this mirror update cause all our environment stops working is it possible to revert this commit, it is better to add this new behavior in a new major version.

**Comment by mnaberez** [comment]
No, it will not be reverted, since spawning processes as the wrong user may have security implications.  You can pin to the version before the change (`supervisor==3.3.3`) if you are not able to change your config file.  The next major version, Supervisor 4, was already released and includes this change as well.  There are no more planned 3.x releases.

**Comment by axot** [comment]
Unfortunately, it is not easy to install 3.3.3 in alpine.

```
/ # apk add supervisor=3.3.3
ERROR: unsatisfiable constraints:
  supervisor-3.3.4-r1:
    breaks: world[supervisor=3.3.3]
```
