### ISSUE TITLE
feature suggestion: turn off log rotation by default

### ISSUE THREAD

**Issue by gkirkpatrick** [Supervisor/supervisor#1236]
To me the primary features that supervisor provides really have nothing to do with log rotation. It seems like a feature that was added to avoid people filling up disks because they don't realize logs need rotation. 

I recently found out that rotation happens when supervisor started beating logrotate to the punch and then not creating the new files with the proper user. Logrotate was configured to do daily rotations and supervisor was configured (by default and with no way of knowing it was doing it) at 50megs. 

My suggestion would be to have rotation turned off by default. 

The docs are also rather ambiguous about what exactly gets rotated. After reading them, I assumed supervisor would only rotate its own log, not any subprocess logs.

[http://supervisord.org/logging.html#activity-log-rotation](url)

If you read that without knowing a priori that the child logs are rotated, you would assume they aren't by default.

I'm happy to take a crack at updating the docs via a PR if that would help, maybe it would save someone some time.

A few other thought came up from all this:

is there a way to find out what supervisord is using as its setttings. I was specifying a specific config file, but something like 

> supervisord --echo_settings

 would have led me to the issue right away. 

And then my final thought would be to drop the multiple locations of finding config files and just make the user specify which one they want to use. I found a lot of issues online where people were having supervisor use config files that they weren't expecting. 

Thanks for the app. Let me know about the PR for the docs.

**Comment by mnaberez** [comment]
> I recently found out that rotation happens when supervisor started beating logrotate to the punch and then not creating the new files with the proper user. Logrotate was configured to do daily rotations and supervisor was configured (by default and with no way of knowing it was doing it) at 50megs.

Supervisor does not include any sort of operating system integration (such as init scripts or system unit files).  That integration is done by others not involved with the project.  Only those people can know whether another program like logrotate is in use and what options to set.

> My suggestion would be to have rotation turned off by default.

The log rotation options defaults have been unchanged for over a decade.  To my knowledge, this is the first time someone has them to be changed.  Since changing it at this point would break a lot of existing configurations, and other users have not voiced this concern, I do not think we will change it.

> The docs are also rather ambiguous about what exactly gets rotated. After reading them, I assumed supervisor would only rotate its own log, not any subprocess logs.

The manual page for the [configuration file](http://supervisord.org/configuration.html#program-x-section-settings) spells out the rotation options for child processes and their defaults.  The example configuration file output by `echo_supervisord_conf` also shows the rotation options for child programs and their defaults.  

> is there a way to find out what supervisord is using as its setttings. I was specifying a specific config file, but something like

Supervisor does not currently have any settings that can be changed dynamically, so the settings can be obtained by reading the configuration file.

> And then my final thought would be to drop the multiple locations of finding config files and just make the user specify which one they want to use.

You can explicitly use the `-c` option when invoking `supervisord` and `supervisorctl` to tell it specifically where to look for a configuration file.  We're unlikely to remove the search behavior because it was requested by users and still seems to be popular in use today (e.g. `virtualenv` users).  

> Let me know about the PR for the docs.

We will review pull requests for documentation changes.
