### ISSUE TITLE
Warning message SETUPTOOLS WILL STOP WORKING in a subsequent release.

### ISSUE THREAD

**Issue by noahlz** [Supervisor/supervisor#1317]
We have a legacy application that we manage using supervisor. Today, when we ran a deploy script that calls `supervisorctl restart <app>` we see the following output

```
/usr/local/lib/python2.7/dist-packages/pkg_resources/py2_warn.py:19: UserWarning: ************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release. Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
```

Before anybody says "upgrade Python, 2.7 is EOL" yes...we are doing just that. However, in the meantime this log output is very noisy.

1) How can we suppress?
2) Is there a likelihood that supervisord completely stops working for some reason in the next few weeks, before we complete the upgrade?

**Comment by noahlz** [comment]
Note, I'm going to check with the pypa/setuptools/issues/1458 before as well.

**Comment by mnaberez** [comment]
> /usr/local/lib/python2.7/dist-packages/pkg_resources/py2_warn.py:19: UserWarning: ************************************************************
You are running Setuptools on Python 2, which is no longer supported

This message [comes from setuptools](https://github.com/pypa/setuptools/commit/79f1694b05a66cc0fbbbf4e72d63d0a340cf6d84).  It appears when you run `supervisorctl` only because it imports `pkg_resources` (a part of `setuptools`).  Supervisor can't remove the import because it's how our plugin loading system works.

> 1. How can we suppress?

This project, Supervisor, can't do anything to influence this message.   You may be able to avoid the warning by upgrading to a Python 3 environment or by downgrading to a version of setuptools from before the warning was introduced.  

> 2. Is there a likelihood that supervisord completely stops working for some reason in the next few weeks, before we complete the upgrade?

The Supervisor project isn't currently doing anything to actively break Python 2, and we are still testing Python 2 on CI.  However, `setuptools` is a dependency of Supervisor, and that error message states that `setuptools` will stop working.

**Comment by noahlz** [comment]
Thanks!
