### ISSUE TITLE
supervisorctl restart

### ISSUE THREAD

**Issue by gaurang101197** [Supervisor/supervisor#1335]
I want to write my program cache to file before it exit, so I have written shut-down hook in java. So whenever I run `sudo supervisorctl restart processName`, my shut-down hook is called. So how much time my process get whenever I run `sudo supervisorctl restart processName` command. My problem is whenever I have large amount of data to write in file before my application exits, my process won't able to write full data to file and it get restarted before it writes cache to file. If is there any property that I can set so that my process get more amount of time before it exits. My process supervisor config is like below :
`[program:processName]`
`command=java -DconfigFile=/home/ubuntu/processName/config.yml -Dlogback.configurationFile=/home/ubuntu/processName/logback.xml -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8111 -jar /home/ubuntu/processName/processName.jar`
`autostart=false`
`autorestart=true`
`stderr_logfile=/home/ubuntu/processName/log/supervisor.log`
`stdout_logfile=/home/ubuntu/processName/log/supervisor.log`
`user=ubuntu`

supervisor version=3.0b2
thanks.

**Comment by mnaberez** [comment]
`supervisorctl stop <name>` or `supervisorctl restart <name>` causes `supervisord` to first send the `stopsignal` (default `SIGTERM`) to the process, then wait up to `stopwaitsecs` (default `10`) for the process to exit before finally resorting to sending `SIGKILL`.  

Your program should trap the stop signal and instead of exiting immediately, it should complete its shutdown activities and then exit.  `supervisord` will wait up to `stopwaitsecs` for it to exit.  See the [configuration guide](http://supervisord.org/configuration.html) for more on `stopsignal` and `stopwaitsecs`.
