### ISSUE TITLE
Adding color to supervisor ?

### ISSUE THREAD

**Issue by yashmehrotra** [Supervisor/supervisor#1360]
I was playing around with supervisor and added tabulation and color in my own fork.

Would you all be interested in something like this ? If you are, I will update my fork and create a PR for this (and make any changes if required)

![Image](https://yashmehrotra.com/images/supervisor-new.png)

Ref: https://yashmehrotra.com/post/2018-02-25-coloring-supervisor/

**Comment by mnaberez** [comment]
Hi, thanks for this offer and suggestion.  I do not think we can use your fork because we do not want to add the package dependencies on `tabulate`and such.  However, we have an open pull request (#530) that does pretty much the same without these packages.  I am not sure why we have not merged it yet (maybe it needed tests, docs, or something minor) but it is open and should get merged eventually.  If you are up for it, please try that patch also and leave a comment there if you find any issues with it.  Thanks!

**Comment by yashmehrotra** [comment]
@mnaberez Sure, I understand your concern. The extra packages was the reason I didn't create a PR in the first place.
Thanks for pointing me to the patch, will take a look :)
