### ISSUE TITLE
Add `StreamHandler` for `stdout` and `stderr` program logging.

### ISSUE THREAD

**Issue by mrmachine** [Supervisor/supervisor#1371]
I'm trying to run supervisor (to have it run multiple twisted processes via supervisor numprocs, load balanced behind nginx). Logging goes to `/dev/stdout` and `/dev/stderr` with rotation disabled to avoid illegal seek errors. It works fine.

But when I try to run supervisor via `npm-run-all` with the `-l` option (prefix log lines), to run alongside some other processes, supervisor fails to start its programs with:

    INFO spawnerr: unknown error making dispatchers for 'twisted_1': ENXIO

I suppose this is because `npm-run-all` (which starts supervisor) is redirecting stdout/stderr with sockets, as described in #1237

I tested the fix in the related PR #849, which adds a `StreamHandler` for stdout/stderr when the special `stdout` and `stderr` filenames are used, and it fixes my problem. I didn't see any other existing way to add a stream handler for program logs.

It'd be great if this fix could be baked into supervisor because it took me quite some time to even figure out what was going on.

- Supervisor was working great, until I tried to run it via `npm-run-all` (also tried `concurrently`, same problem).
- The supervisor docs only talk about needing to disable rotation when sending logs to stdout/stderr.

The plugin mentioned in #849 also took some time to investigate, and turns out it is not ideal:

- Transforms the output (adds a process name and "stdout" / "stderr" prefix).
- Sends stderr to supervisor stdout, not stderr.
- Current PyPI release is from 2012, and is not compatible with Python 3.
- Appears to flush partial log lines, maybe based on the `buffer_size` (their example configuration has this set to 100).
- Another thing to install.

Since supervisor already configures a different handler for the special `syslog` filename, it seems reasonable to follow that precedent for `stdout` and `stderr` to improve supervisor compatibility with environments that are already redirecting stdout and stderr with sockets.

I know #1237 was closed as a duplicate of #849 which was closed because file based stdout logging is already possible, and an event based plugin already exists. But please reconsider fixing this issue properly in supervisor.

It would probably also make the current caveats about disabling rotation when logging to stdout redundant.

**Comment by mnaberez** [comment]
> I know #1237 was closed as a duplicate of #849 which was closed because file based stdout logging is already possible, and an event based plugin already exists. But please reconsider fixing this issue properly in supervisor.

Please don't open duplicates of existing rejected issues.

**Comment by XXLuigiMario** [comment]
This is a perfectly valid issue, which I too have been running into. Writing to `/dev/stdout` and `/dev/stderr` causes all sorts of non-trivial issues depending on the presence of a pseudo-TTYs, permissions, etc. This is especially notable in the case of containers. Read: https://github.com/moby/moby/issues/31243, https://github.com/moby/moby/issues/11462

Setting `stdout_logfile` to `/dev/stdout` on Docker forces containers to be started with the `--tty` option and the application be run as root or as a user in the `tty` group. These seem like excessive requirements for the privilege of redirecting the output of subprocesses out of stderr/stdout.

I too found the plugin in #849 to be unfit fpr these purposes, namely because it's not compatible with Python 3, output is transformed in a non-configurable and undesirable manner and stderr is sent to stdout.
