### ISSUE TITLE
Website not working on HTTPS (https://supervisord.org/)

### ISSUE THREAD

**Issue by rafaponieman** [Supervisor/supervisor#1384]
Only http://supervisord.org/ works, https://supervisord.org/ is timing out.

Supervisor is awesome. Thank you!

**Comment by mnaberez** [comment]
Please see #1131 and #947.  The owner of the domain has not responded to questions about this and several other issues.  I last tried to contact him about one year ago (#1241) and he did not reply.  However, there is a mirror of the docs that can be viewed over HTTPS here: https://supervisord.readthedocs.io/en/latest/.  I'm going to close this issue because it is not about the Supervisor software itself, and I don't think there's anything we can do about it.

**Comment by rafaponieman** [comment]
Oh, thank you @mnaberez too bad the owner is not responding. Thank you for the detailed reply, and I'm sorry I hadn't seen the existing issues, only searched on open ones assuming there was something that could be done about it.
