### ISSUE TITLE
Logs only updated when I restart the program

### ISSUE THREAD

**Issue by myounus96** [Supervisor/supervisor#1394]
I have around 10 programs managed by supervisor, but for 2 the logs only updating when I restart the service, what can be the issue.

supervisod version: 3.3.1
system: linux ubuntu

**Comment by mnaberez** [comment]
> I have around 10 programs managed by supervisor, but for 2 the logs only updating when I restart the service

Sometimes programs behave differently when run from a terminal vs. under `supervisord`.  A common issue is a program is buffering its output.  Since 8 seem to be updating but 2 do not, perhaps those 2 are buffering.

If a program is buffering its output, you may not see anything from it until it decides to flush its buffer.  The flush usually occurs after some amount of data has been buffered, or before the program is about to exit.  This may explain why you see the output finally appear in the log file after stopping or restarting the process.

For Python programs, you can try explicitly flushing stdout with `sys.stdout.flush()` in the program or running it unbuffered with `python -u` (or [PYTHONUNBUFFERED](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONUNBUFFERED)).  Other kinds of programs will require other solutions.
