### ISSUE TITLE
Error tail -f stdout and stderr. UI info with "Error response. Error code 410. Message: Gone."

### ISSUE THREAD

**Issue by Poeticphysicist** [Supervisor/supervisor#1406]
I set program command as following:
[program:test]
command=sudo -u python -i /path/to/python -u /path/to/test.py XXX
stderr_logfile=/root/logs/XXX-stderr.log
stdout_logfile=/root/logs/XXX-stdout.log

But when I open "Tail -f Stdout" or "Tail -f Stderr" on UI of inet_http_server, it comes out :
"Error response

Error code 410.

Message: Gone."

Seems not finding log files...

I can find log files "/root/logs/XXX-stdout.log" and "/root/logs/XXX-stderr.log" locally. There are infos in those  files.
It is OK to run "tail -f /root/logs/XXX-stdout.log" with command lines.

I have no idea why infos are missing on UI.

I installed supervisor-4.2.1 in centos8 with python3.6.

**Comment by mnaberez** [comment]
> command=sudo -u python -i /path/to/python -u /path/to/test.py XXX

The configuration file has a `user=` option to switch the user, which is preferable to the above.  The above command might work but is probably not good idea, as using `sudo` to change the user may result in the subprocess having greater privileges than `supervisord` itself.  This can create a situation where `supervisord` is unable to control the subprocess, e.g. it may get permission denied (`EPERM`) when trying to signal it.

> But when I open "Tail -f Stdout" or "Tail -f Stderr" on UI of inet_http_server, it comes out :
> "Error response
> 
> Error code 410.
> 
> Message: Gone."

Here's what I tried to duplicate this.

```
$ supervisord --version
4.2.1

$ cat supervisord.conf
[supervisord]
nodaemon = true

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:find]
command = find /
stdout_logfile = /tmp/find.log
startsecs = 1
autostart = false
autorestart = false

$ supervisord -c supervisord.conf 
2021-03-13 12:14:07,167 INFO Increased RLIMIT_NOFILE limit to 1024
2021-03-13 12:14:07,176 INFO RPC interface 'supervisor' initialized
2021-03-13 12:14:07,176 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2021-03-13 12:14:07,176 INFO supervisord started with pid 29166
```

I opened a browser to `http://127.0.0.1:9001`.

I clicked on "Tail -f Stdout".

The UI shows "Error code 410. Message: Gone".  That is expected.  Since the config file has `autostart = false`, the process has never been started and no log files have been created.  

I clicked "Start" to start the process.
I clicked "Tail -f Stdout" again.

Now the process is running and the log exists.  I clicked "Tail -f Stdout" again and it still showed 410 Gone.  That is not expected.  I don't think the browser even tried to do the request.  When I forced the refresh (Ctrl + Shift + R), I saw the log output.

I think the issue here is that the browser is caching the 410 Gone, which is a reasonable thing for it to do.  We might want to instead return 404 Not Found here since the log file being missing may be a temporary condition.

**Comment by tangtang666** [comment]
thanks, i have the same questions,just forced the refresh can solved it.
