### ISSUE TITLE
The graphical interface cannot use tail -f, help me, that you

### ISSUE THREAD

**Issue by wfwf1990** [Supervisor/supervisor#1443]

**Comment by mnaberez** [comment]
A log file must exist on disk in order for the `tail` commands to work.  In a `[program:x]` section of the config file, ensure that `stdout_logfile` and `stderr_logfile` are set to files that can read.  If the files are set to `none` or a special file like `/dev/stdout` then the `tail` commands won't work because there is nothing for them to read.
