### ISSUE TITLE
Access supervisor xrpc interface from other xrpc interface

### ISSUE THREAD

**Issue by manuel2258** [Supervisor/supervisor#1461]
Hi,

I have a question about about extending supervisord per xrpc plugins.

Basically what I would like to do is write a restartProcess function which stops and starts a process from within the supervisord process, the idea being that a process managed by supervisord can restart itself using the xrpc interface, so calling stop and start separately over that process won't work.
Therefor I would like to access the "supervisor" xrpc interface from my own xrpc plugin.

Spending some hours looking through the code and the already existing 3rdparty plugins, I found no good way of achieving my goal. 

Ideally I would want something like this function from the controller interface: https://github.com/Supervisor/supervisor/blob/master/supervisor/supervisorctl.py#L246

So is my Idea of accessing the "main" supervisor xrpc from another xrpc plugin even possible,  or are the xrpc classes wrapped in a way that makes calling them manually from the same process impossible?

I hope I could somewhat understandable describe my issue, nevertheless already thanks for helping me out!

**Comment by mnaberez** [comment]
> Basically what I would like to do is write a restartProcess function which stops and starts a process from within the supervisord process, the idea being that a process managed by supervisord can restart itself using the xrpc interface, so calling stop and start separately over that process won't work.

The usual way this is done is by the `autorestart` option.  Supervisor will automatically restart a subprocess if `autorestart = true` is set in the `[program:x]` section of the config file.  If so configured, the subprocess wishing to restart itself can just exit.  `supervisord` will detect this via `SIGCHLD` and spawn it again.

> Therefor I would like to access the "supervisor" xrpc interface from my own xrpc plugin.

I'm not aware of a way that an `rpcinterface` plugin can reach into another `rpcinterface` plugin.  Since an `rpcinterface` plugin receives a [`Supervisor`](https://github.com/Supervisor/supervisor/blob/499fc10087a42ad530394ef233baaf1fc6e756f6/supervisor/supervisord.py#L48) instance in its constructor, it may actually be possible to get to it somehow, but it would be convoluted.  However, the main XML-RPC commands like `supervisor.stopProcess()` are themselves implemented in an `rpcinterface` plugin called [`SupervisorNamespaceRPCInterface`](https://github.com/Supervisor/supervisor/blob/499fc10087a42ad530394ef233baaf1fc6e756f6/supervisor/rpcinterface.py#L47).  Your `rpcinterface` plugin could create its own instance of that class, subclass it, etc. 

That said, a subprocess of `supervisord` can't really ask `supervisord` to stop or restart itself using XML-RPC because XML-RPC is a request/response protocol.  The subprocess can make the request, but then the subprocess will be killed by `supervisord` before an XML-RPC response can be returned to it.  So, the process can never receive the response.  This may not necessarily be a problem but it will likely cause `supervisord` to log error messages.

**Comment by julien6387** [comment]
For your information, I am aware of a way to use the Supervisor `rpcinterface` from a plugin because I needed that in mine ([Supvisors](https://github.com/julien6387/supvisors)).

From the `supervisord` object provided by Supervisor when calling your plugin factory, use the following script: 
```
handler = supervisord.options.httpservers[0][1].handlers[0]
#handler = handler.handler
supervisor_rpc_interface = handler.rpcinterface.supervisor
```

Please note that the line in comment is a must-have if username / password are set in Supervisor configuration.
In order to know if username / password are set, check:
```
server_config = supervisord.options.server_configs[0]
server_config['username']
```

This is a pretty ugly dip into Supervisor bowels but it works...
(source: https://github.com/julien6387/supvisors/blob/master/supvisors/infosource.py)

By the way, I had implemented a `restart_process` XML-RPC [here](https://supvisors.readthedocs.io/en/0.10/xml_rpc.html#supvisors.rpcinterface.RPCInterface.restart_process).
But it is a bit of over-engineering if you have only one node to manage or non-distributed applications.

In your own plugin and using the `supervisor_rpc_interface` got previously, a `restartProcess` XML_RPC should look just like this:
```
def restartProcess(self, namespec, wait=True):
    supervisor_rpc_interface.stopProcess(namespec)
    supervisor_rpc_interface.startProcess(namespec, wait)
```

**Comment by manuel2258** [comment]
Thanks @mnaberez and @julien6387 for the details answers.
What worked for us pretty reliable was just killing the process and letting it be restarted by supervisord, the way you pointed it out.

I also dig a bit into supervisord's code when I initially looked into and played a bit around with the internal http handlers the way @julien6387 pointed out, but stopped that as it got a bit ugly pretty fast.

But still thanks a lot for the answers and also both of you for your great projects!
