### ISSUE TITLE
supervisor process been killed

### ISSUE THREAD

**Issue by sangensong** [Supervisor/supervisor#1469]
Here is my operation:
```
>> ps aux|grep python
root     12689  0.0  0.0 112716  2272 pts/1    S+   00:35   0:00 grep --color=auto python3
root     13806  0.0  0.2 247568 20244 ?        Ss   Nov02   0:33 /usr/local/bin/python3.7 /usr/local/bin/supervisord -c /usr/local/supervisor/supervisord.conf
root     14120  1.7  0.6 1315508 52972 ?       Sl   Nov02  31:58 /usr/local/bin/python3.7 /usr/local/ba/run.py
>> kill -9 13806  # this is supervisor's process id
>> supervisorctl restart ba
http://localhost:9001 refused connection
>> supervisorctl stop ba
http://localhost:9001 refused connection
```

When I kill the supervisor process, the supervisor can't work.

**Comment by mnaberez** [comment]
Supervisor is a client/server system in which the client `supervisorctl` sends commands to the server `supervisord`.  Above, the command `kill -9 13806` sends `SIGKILL` to the `supervisord` server process, which causes it to immediately terminate.  The subsequent `supervisorctl` client commands emit error messages indicating that they cannot communicate with `supervisord` server.  That is expected, since the `supervisord` server process is not running anymore.

If you want `supervisord` to somehow be automatically respawned after you `kill -9` it, you'll need to investigate how `supervisord` is installed on your computer.  The Supervisor project itself doesn't provide init scripts or other sorts of operating system integration.  If you installed Supervisor with a command like `apt` or `rpm`, the authors of the package may have provided such integration, but it wasn't written by the Supervisor developers and is not something the Supervisor developers can help troubleshoot.
