### ISSUE TITLE
Readline not enabled for supervisorctl fg <service>?

### ISSUE THREAD

**Issue by knpwrs** [Supervisor/supervisor#1494]
1. When I run a rails app with byebug enabled I am able to enter commands and navigate up and down my byebug command history with the arrow keys.
2. When I run the same rails app under supervisor and then foreground the service (`supervisorctl fg rails`) I am unable to use the arrow keys as expected. Pressing the up key, for instance, enters `^[[A`:

  ![image](https://user-images.githubusercontent.com/174864/154372570-4df1246b-6404-41f2-b4f5-47870bd192c5.png)

Is there a way to make my arrow keys behave under supervisor as they do when not under supervisor?

**Comment by mnaberez** [comment]
> Is there a way to make my arrow keys behave under supervisor as they do when not under supervisor?

Not with the current [implementation](https://docs.python.org/2/library/functions.html#raw_input):

https://github.com/Supervisor/supervisor/blob/602d6f574a3cba021ec3865bee6ebe20149fff26/supervisor/supervisorctl.py#L1372-L1374

**Comment by knpwrs** [comment]
So it seems like using the arrow keys works when running `fg rails` from the supervisor shell (launched via `supervisorctl -c ./workbench/supervisord.conf`), but the arrow keys do not work when going directly to foreground, bypassing the supervisor shell (via `supervisorctl -c ./workbench/supervisord.conf fg rails`).

This is an example of going to the supervisor shell first and then using `fg rails`:

https://user-images.githubusercontent.com/174864/155399871-ba0a2d2d-a752-46ad-940e-1b3e839ec801.mov

**Comment by knpwrs** [comment]
As a workaround it appears that using [`rlwrap`](https://github.com/hanslub42/rlwrap) works:

```
rlwrap supervisorctl -c ./workbench/supervisord.conf fg rails
```

**Comment by mnaberez** [comment]
There are two different issues in represented in this ticket.  There's the original question:

> Is there a way to make my arrow keys behave under supervisor as they do when not under supervisor?

The answer is no because of the [implementation](https://github.com/Supervisor/supervisor/issues/1494#issuecomment-1042405410).  The user input is line buffered by `supervisorctl`, so the escape sequences for the arrow keys aren't sent to the remote process.  They're handled by `supervisorctl`.  This means that programs such as text editors, which expect character input, won't work.

The second issue is this one:

> So it seems like using the arrow keys works when running fg rails from the supervisor shell (launched via supervisorctl -c ./workbench/supervisord.conf), but the arrow keys do not work when going directly to foreground, bypassing the supervisor shell (via supervisorctl -c ./workbench/supervisord.conf fg rails).

This would seem to indicate that the local readline (the one used by `raw_input` in the `supervisorctl` process) isn't being used for some reason under that invocation.

**Comment by knpwrs** [comment]
Interesting. `rlwrap` works for me for now. Thank you!
