### ISSUE TITLE
License / Copyright discrepancy for http_python.py

### ISSUE THREAD

**Issue by sjvp** [Supervisor/supervisor#1501]
Hi - I'm trying to get approval for us to use supervisor, as is a perfect fit where a docker container needs to run/manage/restart multiple processes (in K8s would be side-cars but for docker-only have to be managed in the same container).

Our approvers have come back with a question on the text included in LICENSES.txt and COPYRIGHT.txt for http_python.py.

There is a difference between the wording in LICENSES.txt (lines 45->76) vs COPYRIGHT.txt (lines 16-26) - the latter being a subset.

Is there a reason for the discrepancy? Can the text be aligned between the two files?

**Comment by mnaberez** [comment]
> There is a difference between the wording in LICENSES.txt (lines 45->76) 

https://github.com/Supervisor/supervisor/blob/602d6f574a3cba021ec3865bee6ebe20149fff26/LICENSES.txt#L45-L76

> vs COPYRIGHT.txt (lines 16-26)

https://github.com/Supervisor/supervisor/blob/602d6f574a3cba021ec3865bee6ebe20149fff26/COPYRIGHT.txt#L16-L26

**Comment by mnaberez** [comment]
> Is there a reason for the discrepancy? 

It looks like the file `LICENSES.txt` was intended to collect licenses and `COPYRIGHT.txt` was intended collect the respective copyright holders.  

The file `LICENSES.txt` seems to have the complete license for RDFLIB, which includes copyright information.  The file `COPYRIGHT.txt` seems to include just the part of that license that pertains to copyright.  

> Can the text be aligned between the two files?

The text related to RDFLIB's copyright looks identical between the two files.  Non-copyright information for RDFLIB seems to have been omitted from `COPYRIGHT.txt` but is present in `LICENSES.txt`.  That seems to have been done consistently (e.g. compare Supervisor and Medusa between the files).

I'm not sure if there was some legal or other motivation to have `COPYRIGHT.txt` in addition to `LICENSES.txt`, since `COPYRIGHT.txt` seems to just be a subset of the information in `LICENSES.txt`.  Since the two files seem to have been created this way deliberately, I'd rather not change them.

The original author of these files is Chris McDonough (@mcdonc).  He has not been active on this issue tracker for several years, so please contact him directly if you need to request changes to the license or copyright files.

**Comment by mcdonc** [comment]
I have no issues with chopping the COPYRIGHT.txt file down to include only the copyright holder names, if that fixes the problem.

**Comment by sjvp** [comment]
Thanks - appreciate the quick turnaround 👍
