### ISSUE TITLE
playsound can't work when using supervisor

### ISSUE THREAD

**Issue by momohuangsha** [Supervisor/supervisor#1537]
Hi~
It does not work when executing Python programs (playing audio with playsound) through Supervisor
Other functions are normal except playsound does not work
my config like this:
[program:ocr]
directory=/home/firefly/worspace/PPOCR
command=/home/firefly/anaconda3/envs/py37/bin/python /home/firefly/workspace/PPOCR/ttt.py
numprocs=1
autostart=true
autorestart=true
startretries=5
exitcodes=0
stopsignal=KILL
stopasgroup=true
killasgroup=true
stopwaitsecs=3
redirect_stderr=true
stdout_logfile=/home/firefly/workspace/PPOCR/supervisor.log
user=firefly

**Comment by mnaberez** [comment]
> It does not work when executing Python programs (playing audio with playsound) through Supervisor
Other functions are normal except playsound does not work

Sometimes programs behave differently when run under `supervisord` versus a shell prompt.  

This is usually caused by either:

 - Differences in the user or environment.  Even if you configure the same user in `supervisord.conf` as you are using for your shell, the program may have a different environment when run under `supervisord`.  You can test this by comparing the output of `/usr/bin/env` on the shell with the output of `command = /usr/bin/env` under `supervisord`.  Programs run under `supervisord` [only inherit](http://supervisord.org/subprocess.html#subprocess-environment) the environment from which `supervisord` was started, whereas your shell probably does additional processing like reading a `.profile` file.  Perhaps required environment variables are missing or different.

 - The program behaves differently when run under a TTY versus when not.  Normally, programs run directly from a shell prompt detect a TTY.  Programs run under `supervisord` do not have a TTY.  Programs sometimes [detect](https://docs.python.org/3/library/os.html#os.isatty) if they are running under a TTY and act differently.

I would look to see if `playsound` prints any error message or offers any "verbose" or "debug" options that might give clues about what it is doing.  This issue is unlikely one that the Supervisor developers can do anything about, as it's likely specific to `playsound` and/or your system.
