### ISSUE TITLE
Python 3.8 issue with Supervisor

### ISSUE THREAD

**Issue by waldeckerthefirst** [Supervisor/supervisor#1571]
Hello, i am migrating from CakeResque to Supervisor for MISP(https://github.com/MISP/MISP/blob/2.4/docs/background-jobs-migration-guide.md). I am currently using python3.8 on RedHat 8.6. I have installed supervisor 4.2.2.

I get the following error while trying to start with python3.8:
supervisord[30988]:     from pkg_resources import load_entry_point
supervisord[30988]:   File "/usr/lib/python3.8/site-packages/pkg_resources/_init_.py", line 3252, in <module>
supervisord[30988]:     def _initialize_master_working_set():
supervisord[30988]:   File "/usr/lib/python3.8/site-packages/pkg_resources/_init_.py", line 3235, in _call_aside
supervisord[30988]:     f(*args, **kwargs)
supervisord[30988]:   File "/usr/lib/python3.8/site-packages/pkg_resources/_init_.py", line 3264, in _initialize_master_working_set
supervisord[30988]:     working_set = WorkingSet._build_master()
supervisord[30988]:   File "/usr/lib/python3.8/site-packages/pkg_resources/_init_.py", line 583, in _build_master
supervisord[30988]:     ws.require(_requires_)
supervisord[30988]:   File "/usr/lib/python3.8/site-packages/pkg_resources/_init_.py", line 900, in require
supervisord[30988]:     needed = self.resolve(parse_requirements(requirements))
supervisord[30988]:   File "/usr/lib/python3.8/site-packages/pkg_resources/_init_.py", line 786, in resolve
supervisord[30988]:     raise DistributionNotFound(req, requirers)
supervisord[30988]: pkg_resources.DistributionNotFound: The 'supervisor==4.1.0' distribution was not found and is required by the application
systemd[1]: supervisord.service: Control process exited, code=exited status=1
systemd[1]: supervisord.service: Failed with result 'exit-code'.

While using python3-3.6 it is working. From the EPEL repo i cannot find supervisor 4.1.0.

**Comment by mnaberez** [comment]
> While using python3-3.6 it is working. From the EPEL repo i cannot find supervisor 4.1.0.

The Supervisor developers only publish Python packages to [PyPI](https://pypi.org/project/supervisor/).  Other types of packages are developed by other people who not part of the Supervisor project.  The Supervisor packages currently on PyPI do run on Python 3.8 and the main branch is [tested on 3.8 on CI](https://github.com/Supervisor/supervisor/actions?query=branch%3Amain).  

This issue seems to either be with packages not published by the Supervisor developers, or something particular to this installation.  Either way, the Supervisor generally do not have enough bandwith to help troubleshoot individual installations and can't help with this, sorry.
