### ISSUE TITLE
Running it on a read-only file system

### ISSUE THREAD

**Issue by skhaz** [Supervisor/supervisor#1585]
Is it possible to run the supervisor on a read-only filesystem?

Context: I'm using it to run a NodeJS application and Nginx together, and one of the requirements is to run as non-root on a read-only filesystem.

My config

```
[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=user

[program:nginx]
command=/bin/sh -c "envsubst '\$PORT \$APP_PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
autostart=true
autorestart=true
priority=100
stdout_events_enabled=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_events_enabled=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=QUIT
```

However, when I run it, I got the error

> PermissionError: [Errno 13] Permission denied: '/var/log/supervisor/supervisord.log'

When I set the log to stdout, I got the error

> [PermissionError: [Errno 13] Permission denied: '/var/log/supervisor/migrate-stdout...'

I was reading the documentation and couldn't find any setting that I could use to completely redirect or disable the supervisord logs.

Is it possible?

**Comment by skhaz** [comment]
The error was my fault; I forgot to redirect the logs to stdout and stderr. By doing this, I could run as non-root on a read-only filesystem.

**Comment by damacadmin** [comment]
Space



Overview
[Try for free](https://www.jetbrains.com/space/app/new/)
All-in-One Solution
for Software Teams and Projects
Space is a fully integrated toolchain that connects the software development pipeline, communication, and project management.

 Everything your company needs in one tool
 Covers the processes of the whole team
 Scales with your organization
Give Your Software Team a Digital Home for Free
[Try for free](https://www.jetbrains.com/space/app/new/)
Develop Software and
Collaborate in One Place
No matter the size of your business or how long you have been around, there are always things you need to manage. To help you focus on what's important, we’ve created Space, an integrated team environment.

Space unifies tooling and information across your company, bringing more effective collaboration to your team.
Manage all the aspects of your tech business from source control hosting to running meetings.
Communicate in chats, collaborate on projects, share knowledge, and build and deliver software together.
Preview image of space overview video
Software Development
Covering [software development](https://www.jetbrains.com/space/features/software-development.html) pipelines at every scale, Space includes everything you need to speed up production, giving developers the freedom to grow, discover, collaborate, and create:

Source code hosting (Git)
Code review, including merge requests and quality gates
Automation jobs for building and deploying applications
Package and container registries for publishing artifacts
Plugins to connect Space to your favorite IntelliJ-based IDEs
Software Development
Business Management
Manage and grow your business faster with Space. Collaborate, build software, and keep everything easily accessible in one platform.

Forget about having to rely on multiple tools and subscriptions. Space offers a broad toolchain for coordinating all aspects of your business, including:

Software development
Project management
Communications
Team management
Business Management
Project management
[Manage projects](https://www.jetbrains.com/space/features/project-management.html) faster and transparently with Space. Plan, schedule, collaborate, and meet deadlines easily.

Space helps you to optimize the whole project management workflow and collaboration process:

Checklists for planning
An issue tracker for task management
Issue boards for visualizing progress
To-do lists for personal task tracking
Project management
Communications
Streamline [communication](https://www.jetbrains.com/space/features/chats-and-documents.html) and keep everyone on the same page by sharing information with your team.

Space integrates various tools for easier communication:

Chats and channels
Collaborative documents and blogs
Meeting management
Shared team calendars
Communications
Team Management
[Manage your team](https://www.jetbrains.com/space/features/team-management.html), absences, and your company’s organizational structure.

Space offers everything your company needs to ensure smooth and transparent collaboration:

Team directory with member profiles
Vacation and absence management
Managing personal and team calendars
Team Management
The Complete Solution for Software Teams and Projects
Perfect for Tech Companies
Space covers the entire software development life cycle. It has everything from source code hosting to package management.

Integration with JetBrains IDEs
Review and comment on code using the power of IDE navigation. Manage your merge requests and code reviews without leaving your IDE.

Scales with Your Business
You can easily scale Space as your company grows and more teams join the platform. Space can be customized and extended to meet your exact needs.

Cost Saving Solution
Instead of paying for multiple solutions, get one platform with the complete software development, project management, and communication toolchain your business needs.

Designed to Streamline Collaboration
Space removes the silos between different teams and specialists by connecting development, project management, and collaboration features.

Ideal for Remote Work
Space will help you run all your business processes online, keeping everyone informed and up to date without overloading them with irrelevant information.

Get started with the free cloud plan for an unlimited number of users, and then [upgrade](https://www.jetbrains.com/space/buy/?billing=yearly#cloud) when you're ready.

Watch the Space Overview Video
Get started with Space today
Give Your Software Team a Digital Home for Free

[Try for free](https://www.jetbrains.com/space/app/new/)
Discover How Other Software Teams Benefit From Using Space
Makery
Rather than using a multitude of individual tools, we’ve always preferred integrated environments. We started looking for a new digital home, and when we heard about Space at KotlinConf, we really liked the concept. So we decided to sign up. [Read story](https://www.jetbrains.com/company/customers/experience/makery/)

Andras Kindler
Andras Kindler,

Co-Founder,
Makery

AmberCore Software Ltd
Communication has become faster since we started using Space. I think the deciding factors in choosing to go with Space were its ease of use and versatility. [Read story](https://www.jetbrains.com/company/customers/experience/ambercore/)

Anna Vinogradova
Anna Vinogradova,

Chief Marketing Officer,
AmberCore Software Ltd

Get a Complete Solution for Software Development by Connecting JetBrains IDEs to Space
50% Discount on JetBrains IDEs and .NET Tools for Startup Companies

Is your company less than 5 years old? If so, you can benefit from our special offer for startups and get 50% off all your JetBrains tools.

With this discount, you can purchase up to 10 product licenses over a period of 60 months. Connect your JetBrains IDEs to Space to get access to your repositories, code reviews, and Automation (CI builds).

Startup Discount Requirements
Your company is privately held.
You can confirm that it was established less than 5 years ago.
Your company has a website or existing public references on the internet.
Get 50% off on all JetBrains Tools

[Apply for Discount](https://www.jetbrains.com/shop/eform/startup/)
Products
[IDEs](https://www.jetbrains.com/products/#type=ide)
[.NET & Visual Studio](https://www.jetbrains.com/products/#tech=dotnet)
[Team Tools](https://www.jetbrains.com/products/#type=team)
[Plugins](https://plugins.jetbrains.com/)
[Education](https://www.jetbrains.com/edu-products/)
[Languages](https://www.jetbrains.com/products/#type=language)
[All products](https://www.jetbrains.com/products/)
Solutions
[C++ Tools](https://www.jetbrains.com/cpp/)
[Data Tools](https://www.jetbrains.com/data-tools/)
[DevOps](https://www.jetbrains.com/devops/)
[Education](https://www.jetbrains.com/education/)
[Game Development](https://www.jetbrains.com/gamedev/)
[Software Development](https://www.jetbrains.com/space/solutions/software-teams/)
[Tools For Business](https://www.jetbrains.com/store/business/)
[Quality Assurance](https://www.jetbrains.com/quality-assurance-solutions/)
Initiatives
[Kotlin](https://www.jetbrains.com/opensource/kotlin/)
[JetBrains Mono](https://www.jetbrains.com/lp/mono/)
[JetBrains Research](https://www.jetbrains.com/research/)
[Open Source Projects](https://www.jetbrains.com/opensource/)
Community
[Academic Licensing](https://www.jetbrains.com/community/education/)
[Open Source Support](https://www.jetbrains.com/community/opensource/)
[User Groups](https://www.jetbrains.com/community/user-groups/)
[Events Partnership](https://www.jetbrains.com/community/events-partnership/)
[Developer Recognition](https://www.jetbrains.com/community/dev-recognition/)
Resources
[Sales Support](https://www.jetbrains.com/support/sales/)
[Product Support](https://www.jetbrains.com/support/)
[Licensing FAQ](https://sales.jetbrains.com/hc/en-gb/)
[Documentation](https://www.jetbrains.com/help/)
[Early Access](https://www.jetbrains.com/resources/eap/)
[Events and Webinars](https://www.jetbrains.com/company/conferences/)
[Newsletters](https://www.jetbrains.com/resources/newsletters/)
[Industry Reports](https://www.jetbrains.com/resources/industry-reports/)
[Blog](https://blog.jetbrains.com/)
[Desktop Art](https://www.jetbrains.com/company/brand/desktop-art/)
Company
[About](https://www.jetbrains.com/company/)
[Contacts](https://www.jetbrains.com/company/contacts/#headquarters-international-sales)
[Careers](https://www.jetbrains.com/careers/apply/)
[News](https://www.jetbrains.com/company/press/)
[Customers & Awards](https://www.jetbrains.com/company/customers/)
[Our Commitment](https://www.jetbrains.com/company/commitment/)
[Brand Assets](https://www.jetbrains.com/company/brand/)
[Partners and Resellers](https://www.jetbrains.com/company/partners/)
Saudi Arabia
English
[Privacy & Security](https://www.jetbrains.com/privacy-security/)
[Terms of Use](https://www.jetbrains.com/legal/docs/company/useterms.html)
[Trademarks](https://www.jetbrains.com/legal/trademarks/)
[Legal](https://www.jetbrains.com/legal/)
[Genuine Tools](https://www.jetbrains.com/genuine-tools/)
Copyright © 2000-2023 JetBrains s.r.o.
Developed with drive and [IntelliJ IDEA](https://jetbrains.com/idea)

**Comment by skhaz** [comment]
@antfig, I ended up running it inside the container as root, unfortunately. The supervisor tried to write in several places, and I had no time to track which files were.

**Comment by antfig** [comment]
Thanks for the Reply @skhaz ;)
