### ISSUE TITLE
supervisor not working

### ISSUE THREAD

**Issue by shubhamiksha** [Supervisor/supervisor#1654]
CRIT uncaptured python exception, closing channel <POutputDispatcher at 127341676956816 for <Subprocess at 127341659653584 with name celery in state RUNNING> (stderr)> (<class 'OSError'>:[Errno 29] Illegal seek [/usr/lib/python3/dist-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3/dist-packages/supervisor/loggers.py|info|327] [/usr/lib/python3/dist-packages/supervisor/loggers.py|log|345] [/usr/lib/python3/dist-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3/dist-packages/supervisor/loggers.py|doRollover|264])

**Comment by russellballestrini** [comment]
The error message you're seeing is related to an OSError with the message [Errno 29] Illegal seek. This error occurs when a file operation is attempted on a file object that does not support seeking, such as a pipe or a socket. In the context of supervisord, this typically happens when it tries to handle log rotation for a process that is writing to a non-seekable output, like a pipe.

Here are some steps you can take to address this issue:

    Disable Log Rotation: Since the error is related to log rotation, you can disable log rotation for the affected process. This can be done by setting stdout_logfile_maxbytes and stderr_logfile_maxbytes to 0, which you have already done. This setting should prevent supervisord from attempting to rotate logs.

    Use a Different Log Driver: If you're running this in a containerized environment, consider using a different log driver that handles log rotation outside of supervisord. For example, Docker's logging drivers can be configured to handle log rotation.

    Redirect Logs to a File: Instead of using /dev/stdout and /dev/stderr, you can redirect logs to a file within the container. This way, supervisord can manage log rotation without encountering the illegal seek error. However, this approach might not be ideal if you rely on container logs being available through standard output.

    Check for Updates: Ensure that you are using the latest version of supervisord and any related packages. There might be bug fixes or improvements that address this issue.

    Review Celery Configuration: If the error is related to a Celery process, review the Celery configuration to ensure that it is not interfering with supervisord's logging. Make sure that Celery's logging is configured to work well with supervisord.

    Custom Log Handling: Implement custom log handling in your application to manage logs more effectively, especially if you have specific requirements for log rotation or retention.

By addressing the logging configuration and ensuring that supervisord is not attempting to rotate logs on non-seekable outputs, you should be able to resolve this error. If the problem persists, consider reviewing the full stack trace and any related configuration files for additional context.
