### ISSUE TITLE
update configuration upon "start"/"restart" if .conf file was changed on disk

### ISSUE THREAD

**Issue by the-efi** [Supervisor/supervisor#441]
Spent a couple of hours for a couple of times because I [wrongly] assume that if I change configuration and issue a restart, my new configuration will take place.

If this breaks some existing behavior, it would be nice to issue a warning between 'stopping' and 'starting'.

**Comment by mnaberez** [comment]
Thanks for this report. We're unlikely to change the behavior because it has worked like this for a long time and changing it may cause problems for some users.  However, your suggestion of a warning could likely happen, and #582 was opened recently suggesting that also.  I'm going to close this issue in favor of #582 mainly because the most recent discussion of this issue is over there.
