### ISSUE TITLE
supervisor under supervisor

### ISSUE THREAD

**Issue by pjz** [Supervisor/supervisor#544]
Is there an example supervisor.conf file for running supervisor under supervisor?  I want the sub-supervisor to run as a particular user instead of root like the main system, and have a different `include=` that points at a dir that user can edit.

Given supervisor's intentional lack of access controls, this seems like a common enough desire to want well documented, if only to show how easy it is.

**Comment by mnaberez** [comment]
It should be possible to run `supervisord` as a subprocess of another `supervisord`.  I'm not aware of anyone doing this but here are the issues that I think will be involved.

All subprocesses run under `supervisord` must run in the foreground, as explained in  [nondaemonizing of subprocesses](http://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses). A `supervisord` instance can be run in the foreground with `-n`.

Each `supervisord` instance would need its own config file.  An explicit path to a config file can be specified with `-c`.

Each `supervisord` instance would need its own socket, logfile, and pidfile.  These options would need to be explicitly configured for each instance:

    [unix_http_server] 
    file=/tmp/supervisor.sock   ; (the path to the socket file)
    
    [inet_http_server]
    ;port=127.0.0.1:9001        ; (ip_address:port specifier, *:port for all iface)
    
    [supervisord]
    logfile=/tmp/supervisord.log ; (main log file;default $CWD/supervisord.log)
    pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)

You may need to tweak some other settings like `stopwaitsecs`.  That must be large enough for the "child" `supervisord` instance to cleanly shut down its subprocesses and exit.  It would need to be longer that the `stopwaitsecs` of the "child" `supervisord` plus a margin (probably 10 seconds or more).

I'm going to close this issue now since it's more of a question than a bug in Supervisor.  Feel free to continue the discussion here or on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).
