### ISSUE TITLE
No memory limits per program or program group

### ISSUE THREAD

**Issue by nkts** [Supervisor/supervisor#586]
I have case, where running program consumed all memory. There's no simple way to add those limits in supervisor "job" configuration.

**Comment by mnaberez** [comment]
There are many different conditions where you might want to restart a process (e.g. a process is using too much memory like above, a process is not responding to HTTP requests, a regular interval, etc).  

Instead of building all of these conditions into `supervisord`, we have the [event listener](http://supervisord.org/events.html) system.  You can write your own event listener to restart your processes on any conditions you need.  

We have a companion package, [Superlance](https://github.com/supervisor/superlance), that has several event listeners.  It includes [memmon](http://superlance.readthedocs.org/en/latest/memmon.html) for monitoring memory usage.
