### ISSUE TITLE
service supervisord restart - it doesn't kill old processes, just add new

### ISSUE THREAD

**Issue by reggin** [Supervisor/supervisor#600]
Then I have each program duplication.

**Comment by thbsolutions** [comment]
I also have this issue, how to fix this?

**Comment by enstain** [comment]
@andriytkachiv  Any luck with it?

**Comment by enstain** [comment]
That's the working solution after all:

1. Manually kill all your old processes

1. Also ask supervisor stop all processes just to be sure we are on a fresh start

    `sudo supervisorctl stop all`

1. Put two new parameters into config belongs to your process with <your_process> name

    ```
    #/etc/supervisorctl/conf.d/your_process.conf

    [program:<your_process>]
    ...
    stopasgroup=true
    stopsignal=QUIT
    ```

1. Make sure supervisor has updated your config:

    `sudo supervisorctl reread`

    `sudo supervisorctl update`

1. Start your process

    `sudo supervisorctl start <your_process>`

1. Check you have no zombies at the process list after `supervisorctl restart <your_process>` by `ps aux | grep "whatever indicates your process"`

**Comment by hyp3rv1p3r** [comment]
Helped me to solve the issue, thanks.

**Comment by kjunggithub** [comment]
@enstain Thanks, works great!

**Comment by fiatjaf** [comment]
The workaround doesn't work here. The processes are not killed. There isn't a notice about the fact that the processes aren't killed either.

Shouldn't this be a basic feature?

**Comment by MihaelIsaev** [comment]
@enstain solution work for me, thanks!

**Comment by proohit** [comment]
@enstain solution worked for me too, thank you !!

**Comment by sayhicoelho** [comment]
Using `kill <PID>` worked for me.

**Comment by soerendip** [comment]
> Manually kill all your old processes

how to find those??

**Comment by proohit** [comment]
> > Manually kill all your old processes
> 
> how to find those??

Try 
`ps -A`
This will display all running processes.
e.g. 
`ps -A | grep java`
Will display all Java processes.

**Comment by chrisspen** [comment]
Why was this closed? Supervisor still has this bug. The basic "stop" action does not stop processes. That's a massive problem.

**Comment by MihaelIsaev** [comment]
@chrisspen as I see `supervisor` works well, but some programs won't stop on `SIGTERM` so we have to specify in config `stopsignal=QUIT` to let `supervisor` know that it should stop the program with `SIGKILL`.

**Comment by tejit2004** [comment]
No, adding `stopsignal=QUIT` and `stopasgroup=true` , still doesn't kills the process.

**Comment by chrisspen** [comment]
Yeah, for now, my workaround is also to run a `killall` command, but that's obviously a hack since supervisor purports to stop it's processes, which it's not.

**Comment by jedmund** [comment]
I'm running into this process with Next.js 13. It worked fine in Next.js 12 b ut something has changed and `stopsignal=TERM` has stopped working. No matter what I do, I can't get supervisor to kill the process anymore.

**Comment by michela** [comment]
Having this issue with python3 uwsgi but never had it with python2 uwsgi

**Comment by kaminosama** [comment]
Here I found the key point of this problem when using supervisor for nextjs SSR mode. 

This issue is related to Supervisor's process management mechanism. When a service is started through Supervisor, its default behavior is to manage the process as a direct child using the fork/exec method. 

However, any child processes spawned by this process (i.e., grandchild processes) are not directly monitored by Supervisor. When a termination signal (such as Ctrl+C or supervisorctl stop) is sent, Supervisor only forwards the signal to its direct child process. As a result, the grandchild process's parent is reassigned to init (PID 1), preventing the signal from reaching the grandchild process and causing it to remain running.

There are two solutions for it.

1. Use the command to launch the real worker process.
    
    For example, when using nextjs, use `/path/to/node_modules/.bin/next start --port={servce_port}` rather than `npm run {your_script}`. The first command will directly run the worker process but the npm command will run three processes in one time.

2. Use the `stopasgroup` and `killasgroup` params. [click here](https://supervisord.org/configuration.html#program-x-section-settings)

Hope this comment can help those who come here. :)

**Comment by bitliner** [comment]
+1 when using `bash -c "poetry run streamlit run app"` as command


tried adding 

stopasgroup=true
stopsignal=QUIT

still it does not work
