### ISSUE TITLE
Env expansion not working in [supervisord] block

### ISSUE THREAD

**Issue by ltagliamonte** [Supervisor/supervisor#645]
I'm trying to use the follow config file:
```
[supervisord]
nodaemon=true
logfile=/var/log/cloud/%(ENV_LOG_ROLE)s/supervisord.log
childlogdir=/var/log/cloud/%(ENV_LOG_ROLE)s

[program:java]
command=java -server %(ENV_ROLES)s %(ENV_JAVA_HEAP_PARAMETERS)s %(ENV_JAVA_GC_PARAMETERS)s %(ENV_JAVA_DEBUG_PARAMETERS)s -jar /opt/jar.jar
redirect_stderr=true
stdout_logfile=/var/log/cloud/%(ENV_LOG_ROLE)s/%(ENV_LOG_ROLE)s.log
stopsignal=KILL
```

only the [superisord] config block is not correctly expanding the environments variables.
I'm on Ubuntu 14.04 using 3.0b2 installed via apt.
I also tried the 3.1.3 installed via pip but it didn't work.
I did a repo checkout and test locally the 3.2 and it seems to work.

Is anything wrong that i'm doing in the conf file? When are you going to release the 3.2?

**Comment by mnaberez** [comment]
> I'm on Ubuntu 14.04 using 3.0b2 installed via apt.
> I also tried the 3.1.3 installed via pip but it didn't work.
...
> Is anything wrong that i'm doing in the conf file? 

No, it was not supported in those versions.

These expansions should be supported since 2d6ca34, which will be released in Supervisor 3.2.  There is [test coverage](https://github.com/Supervisor/supervisor/commit/2d6ca34582a8a07a5dd96ae45ef62cd58a459f4f#diff-fbd382bddb866d15ca6d9009f2b9e7a2R1128) for all the expansions used above, so I am going to close this issue.
