### ISSUE TITLE
XMLRPC prevents persistent connections (Broken pipe)

### ISSUE THREAD

**Issue by sfriesel** [Supervisor/supervisor#650]
The HTTP-Server checks every 500 connections made for connections older than 30 minutes and closes them (https://github.com/Supervisor/supervisor/blob/master/supervisor/medusa/http_server.py#L505) This means it's not possible to keep a persistent connection open as it will be eventually closed after enough newer ones came in.
I think it would be better to check a last used timestamp instead of the creation time

**Comment by mnaberez** [comment]
`supervisorctl` opens a lot of connections but one way I can see to possibly duplicate this issue would be to run to leave `supervisorctl tail -f procname` running (it maintains a persistent connection) and to simultaneously run a bunch of other `supervisorctl` commands which would open and close connections. Eventually the `tail -f` should disconnect if I understand this issue correctly.

I haven't looked at this much myself but your suggestion sounds very reasonable to me.  This issue is in `medusa`, but we have other fixes and patches in our bundled `medusa` code already like c4c2f8bf68fc76a8d8b7f90abe512e0146132bab.  I'd be happy to merge a pull request to fix this if you are able to work on it.

**Comment by sfriesel** [comment]
Command to reproduce: `supervisorctl tail -f <some_process> & sleep 1810 && for i in $(seq 500); do supervisorctl status > /dev/null; done`. This terminates the tail process after 30 minutes 10 seconds.
