### ISSUE TITLE
Remove dependency to pkg_resources (Py3K)

### ISSUE THREAD

**Issue by palmkevin** [Supervisor/supervisor#662]
```pkg_resoures``` is by default not part of the Python 3 distribution (I don't know for Py2). Dependencies to third party modules should be avoided if possible.
Currently ```pkg_resources``` is needed by method ```import_spec``` in option.py

The following implementation of ```import_spec``` uses the (builtin) library ```importlib``` and produces the same output.

```python
    def import_spec(self, spec):
        import importlib
        moduleName, methodName = spec.split(":")
        mod = importlib.import_module(moduleName)
        if not mod:
            raise Exception("No module '%s' found" % (moduleName))
        meth = getattr(mod, methodName)
        if not meth:
            raise Exception("No method '%s' found in module '%s'" % (methodName, moduleName))
        return meth
```

**Comment by mnaberez** [comment]
Supervisor requires `setuptools` for installation on both Python 2 and 3.  `pkg_resources` is provided by `setuptools`, so it will be available wherever Supervisor has been successfully installed.  We've required `setuptools` for install on for many years and hasn't caused any issues being reported to the tracker.

I'm far from a Python packaging expert but the `import_spec` method in `options.py` is the basis for Supervisor's plugin system.  It is important that it keeps working correctly and I'd rather not mess with that if I don't have to.  It seems safer and easier to keep letting `setuptools` handle the implementation for this like we always have rather than try to roll our own.

**Comment by palmkevin** [comment]
I do understand your point, but many products (ours included) embed third party python code in the software package we are distributing to customers. -> We do *not* install these packages into a python interpreter, but extract them and copy the python code in a folder being added to ```PYTHONPATH```.
We have thus no usage of ```setuptools```.
Our software uses more than 20 third party projects (supervisor included), and we had never the need to use ```setuptools```!

BTW: I am running supervisor on Python 3 in production since 2012. At the time I already replaced your implementation of ```import_spec``` in order to make supervisor working in my environment. And it works!

**Comment by mnaberez** [comment]
`setuptools` has been a requirement of Supervisor since at least 3.0a1 (released in 2007).  The type of installation you are describing isn't one we have ever documented as supported, and would have required a patch on all release versions since 2007.  As far as I know, we haven't had other issues reported about needing to remove `setuptools` during all that time.  I see replacing `setuptools`/`pkg_resources` with our own codeas a fairly risk change that could affect a lot of users.  I would rather not make this change.

**Comment by palmkevin** [comment]
If you see it too risky, why not having my solution as a fallback if ```pkg_resources``` is not available?

**Comment by mnaberez** [comment]
`pkg_resources` is provided by `setuptools`, which is a requirement or installing Supervisor since 2007. It is always available.

**Comment by palmkevin** [comment]
Since Python 3.5 there exists an [embedded version of the Python Interpreter](https://docs.python.org/3/using/windows.html#embedded-distribution).
The normal distribution of py35 comes with `setuptools` out of the box (thus no need for external setuptools library).
But the embedded distribution doesn't. Supervisor is thus in a need of an additional dependency for the embedded interpreter only.
Personally, I don't supervisor should require a dependecny to setuptools. Because it  *just* used for the point mentioned in my post.
Please notice also that I am running supervisor on Py3 without setuptools since 4 years now!
(What if you dropped dependency just for py >= 3 ?)
