### ISSUE TITLE
Feature request: Kill process after some time to restart it

### ISSUE THREAD

**Issue by yarikdot** [Supervisor/supervisor#682]
Some (php) processes sometime for any reason stops working and are just waiting. It would be nice to have the ability to kill the process automaticaly and let it to start again.

**Comment by mnaberez** [comment]
Supervisor has an [events system](http://supervisord.org/events.html) and many [plugins](http://supervisord.org/plugins.html) have been written using it.  Rather than building many types of monitoring or restart strategies into Supervisor itself, we encourage them to be written as plugins.

The [Superlance](https://github.com/Supervisor/superlance) package contains some plugins, such as `httpok`, which can make an HTTP request and restart a process based on the result.  

If you want to write your own plugin to restart a process unconditionally after some time, your plugin can periodically call [`supervisor.getProcessInfo`](https://github.com/Supervisor/superlance) to find out how long a process has been running, then call `stopProcess`/`startProcess` to restart it.
