### ISSUE TITLE
Log the fact that using sudo in command makes environment variables go ignored

### ISSUE THREAD

**Issue by fzaninotto** [Supervisor/supervisor#701]
Here is a sample configuration file I used:

```
[program:myapp]
directory=/home/ubuntu/myapp
autostart=false
autorestart=true
environment=
  NODE_ENV=production,
  NODE_PORT=80
stderr_logfile=/var/log/myapp.err.log
stdout_logfile=/var/log/myapp.out.log
user=ubuntu
command=sudo node /home/ubuntu/myapp/api/index.js
```

Before you close this ticket, I know I'm not supposed to use `sudo` in command. The right configuration file is, of course:

```
[program:myapp]
directory=/home/ubuntu/myapp
autostart=false
autorestart=true
environment=
  NODE_ENV=production,
  NODE_PORT=80
stderr_logfile=/var/log/myapp.err.log
stdout_logfile=/var/log/myapp.out.log
user=root
command=node /home/ubuntu/myapp/api/index.js
```

I mean, I know that I musn't use `sudo` in command... after spending one hour trying to understand why supervisor wouldn't use my environment variables. My point is, silently ignoring the `environment` clause in case of `sudo` in command is very counterintuitive. There should at least be a warning in the supervisor logs.

**Comment by mnaberez** [comment]
> My point is, silently ignoring the environment clause in case of sudo in command is very counterintuitive.

`supervisord` has no special handling for `sudo`, it just runs that program like any other.  It is setting your environment variables, but `sudo` is unsetting them.  This is probably the result of an `env_reset` line in your `sudoers` file.  You can see the same effect in a shell:

    $ whoami
    notroot
    $ export FOO=bar
    $ echo $FOO
    bar
    $ sudo bash -c 'echo $FOO'          # this is the effect of env_reset
    
    $ sudo -E bash -c 'echo $FOO'       # see `man sudo` for -E
    bar
    
> There should at least be a warning in the supervisor logs. 

There is no way to do this because it's impossible for `supervisord` to know if the command you specified will result in the environment you want.

**Comment by fzaninotto** [comment]
Fair enough, thanks for replying!
