### ISSUE TITLE
`help reread` is confusing

### ISSUE THREAD

**Issue by ben-page** [Supervisor/supervisor#714]
```
supervisor> help reread
reread                  Reload the daemon's configuration files
supervisor> help reload
reload                  Restart the remote supervisord.
supervisor> help update
update                  Reload config and add/remove as necessary
update all              Reload config and add/remove as necessary
update <gname> [...]    Update specific groups
````

According to the help `reread` reloads and `reload` restarts. This is confusing. Personally, I think the description for `reread` is inaccurate. `reread` doesn't reload, it just reads and displays the changes.

**Comment by mnaberez** [comment]
`reread` does reload the configuration files as the help says, but it doesn't apply the changes to the running configuration.  It makes the new configuration available for the commands `avail`, `add`, and `remove`, which the user can then use to selectively modify the running configuration.

The `update` command is an alternative that does a `reread` and then does the equivalent of `add` or `remove` to bring the running configuration into compliance with the configuration files.

There are two issues open for us to add documentation for this (#720 and #250).  I'm going to close this issue since those are still open.
