### ISSUE TITLE
%(here)s is not avaibled for include config?

### ISSUE THREAD

**Issue by andares** [Supervisor/supervisor#764]
I use supervisord version is 3.3.0, and written include config like:

```
directory = %(here)s/../../../
command = ./call mps:queue start
stdout_logfile = %(here)s/../../../storage/logs/mpsqueue_stdout.log
```

but it can not work:

```
supervisor> reread
ERROR: CANT_REREAD: The directory named as part of the path /home/worker/local/etc/../../../storage/logs/mpsqueue_stdout.log does not exist. in section 'program:mpsqueue' (file: '/home/andares/repos/molbase/pms/vendor/molbaselib/mps/super.ini')
supervisor> 
```

I think it will be '/home/andares/repos/molbase/pms/vendor/molbaselib/mps/../../../storage/logs' but it wasn't.

I saw the issue: [https://github.com/Supervisor/supervisor/issues/81](https://github.com/Supervisor/supervisor/issues/81) it like change was merged to trunk, is it?

**Comment by mnaberez** [comment]
> I saw the issue: #81 it like change was merged to trunk, is it?

A fix for `%(here)s` in included config files was merged to master (see [the changelog](https://github.com/Supervisor/supervisor/blob/abff4cd872d2cbd1b999c1f439fdf83b4695cc6c/CHANGES.txt#L21-L25)).  It is not in Supervisor 3.x because it breaks backwards compatibility.  It will be included in the next major version (Supervisor 4).

**Comment by andares** [comment]
I see, thanks for your comment
