### ISSUE TITLE
Cannot read ENV vars 3.3

### ISSUE THREAD

**Issue by ldynia** [Supervisor/supervisor#769]
// /etc/environment
DEBUG=true

vagrant@vagrant:~> echo $DEBUG
true

// supervisor config file
environment=DEBUG="%(ENV_DEBUG)s"

// supervisor error
Error: Format string 'DEBUG="%(ENV_DEBUG)s"'

**Comment by mnaberez** [comment]
Minimal `supervisord.conf` to reproduce the above:

    [supervisord]
    logfile = /tmp/supervisord.log
    loglevel = debug
    environment = DEBUG="%(ENV_DEBUG)s"
    
    [inet_http_server]
    port = 127.0.0.1:9001
    
    [supervisorctl]
    serverurl = http://127.0.0.1:9001
    
    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
    
    [program:showdebug]
    command = bash -c "echo DEBUG is $DEBUG"
    environment = DEBUG="%(ENV_DEBUG)s"
    startsecs = 0
    autorestart = false



    
Set `DEBUG` environment variable, then start `supervisord` in the foreground:

    $ export DEBUG=true
    $ echo DEBUG is $DEBUG
    DEBUG is true
    $ supervisord --version
    3.3.0
    $ supervisord -n -c /path/to/supervisord.conf
    2016-07-25 08:22:05,555 INFO Increased RLIMIT_NOFILE limit to 1024
    2016-07-25 08:22:05,587 INFO RPC interface 'supervisor' initialized
    2016-07-25 08:22:05,587 CRIT Server 'inet_http_server' running without any HTTP authentication checking
    2016-07-25 08:22:05,587 INFO supervisord started with pid 18944
    2016-07-25 08:22:06,594 INFO spawned: 'showdebug' with pid 18947
    2016-07-25 08:22:06,602 DEBG 'showdebug' stdout output:
    DEBUG is true

Note that there are two places `environment = ` can be set (`[supervisord]` and `[program:x]`).  You didn't say which one you tried, but both work as shown above.

The error you reported was probably caused by `DEBUG` not being present in the environment at the time that `supervisord` was started.  `supervisord` doesn't read or detect changes in files like `/etc/environment`.  It just uses what is present in its environment at the time that it is started.

**Comment by ari23** [comment]
This doesn't work when running supervisor as an upstart/systemd prog. How do we pass env variables in this situation?
