### ISSUE TITLE
Supervisor cli not self aware

### ISSUE THREAD

**Issue by jwdeitch** [Supervisor/supervisor#832]
On Supervisor 3.0b2, Ubuntu 14.04, installed and running under root, 
`sudo service supervisor status` returns 'is not running', However The process is listed in the process snapshot `ps aux`, running as root, in ordinary: 
`/usr/bin/python /usr/bin/supervisord -c /etc/supervisor/supervisord.conf`. 

`sudo service supervisor restart` will complain: 

`Error: Another program is already listening on a port that one of our HTTP servers is configured to use.....`

Thanks in advance for looking at this issue.

**Comment by mnaberez** [comment]
The Supervisor project itself only publishes Python packages to [PyPI](https://pypi.python.org/pypi/supervisor). Our packages are installed with `pip` or `easy_install`.  Our packages don't include init scripts (the bits behind the `sudo service supervisor restart` command you are using).

The distribution packages are created by others that aren't involved with the project.  Only they will be able to solve this issue since the init scripts are something they wrote.  Please report this issue to the maintainers of the package that you are installing.
