### ISSUE TITLE
Suggestion, default var value: %{ENV_VAR:-SomeDefaultValue}

### ISSUE THREAD

**Issue by RRAlex** [Supervisor/supervisor#838]
It would be useful to be able to set a default value, like in bash, when an environment variable is unset instead of dying with an error.

**Comment by mnaberez** [comment]
> It would be useful to be able to set a default value, like in bash, when an environment variable is unset

Supervisor just uses Python to interpolate the `%(ENV_x)s` values.  Doing something like the syntax suggested in the title would require writing a parser, and that's out of scope for this project, sorry.  

> instead of dying with an error

Old versions of Supervisor might have crashed, but since Supervisor 3.2.0 at least, it will exit with an error saying what key is not in the environment and will also print the keys that are in the environment.
