### ISSUE TITLE
Bring down one process when other process gets killed in a group

### ISSUE THREAD

**Issue by mkhetan** [Supervisor/supervisor#874]
Hi,

Is there a way to achieve this using the latest supervisord? I have 2 programs in a group. Both are independent programs. But, I have a requirement that whenever program2 gets killed, program1 gets killed too. Setting stopasgroup=true and   killasgroup=true is not helping.

Thanks,
Mayank

**Comment by mnaberez** [comment]
You can stop the processes in the group individually (e.g. instead of `supervisorctl stop groupname:*` you could issue `supervisorctl stop groupname:processname1` and `supervisorctl stop groupname:processname2`).  Supervisor doesn't have a sort of dependency mechanism that will automatically stop a process when another one stops.

Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
