### ISSUE TITLE
updating PID

### ISSUE THREAD

**Issue by orenmazor** [Supervisor/supervisor#889]
Hey guys, I know the docs say that supervisord will monitor services via a parent-child relationship. but my child can fork itself to a new version (i.e. upgrading code on deploy). as soon as that happens, supervisor no longer monitors my service.

what's the recommended pattern here? many services fork themselves regularly (gunicorn in my case). I have a pidfile and I'd like supervisord to just monitor that pidfile instead of trying to monitor the process itself.

**Comment by ajpen** [comment]
Why not use a [pidproxy program](http://supervisord.org/subprocess.html#pidproxy-program)

**Comment by orenmazor** [comment]
@ajpen reading the pid proxy code, it seems to just spawn whatever is the pid in the pid file and proxy signals to it. It doesn't handle the situation where that pid may change, which is what happens when unicorn/gunicorn forks. 

Testing confirmed this.

**Comment by ajpen** [comment]
If I understand correctly, only gunicorn childprocesses PID would change. The PID for the gunicorn parent does not.

**Comment by ajpen** [comment]
@orenmazor What pidproxy did you use? Why not create your own that re-reads the file, per signal received?

**Comment by mnaberez** [comment]
Please ask questions about using or installing Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list. We use this issue tracker mainly for bugs in Supervisor itself.  I don't have experience with `gunicorn` but some people have asked questions about it on the list in the past, so you might ask there.

`supervisord` has a simple design where it just forks/execs and then monitors the resulting child process via pipes and SIGCHLD.  It isn't intended to monitor programs that can't work this way and this is unlikely to change.  If the process spawned by `supervisord` forks another process and then exits, `supervisord` doesn't have any way of dealing with this and likely never will.  The process spawned by `supervisord` can replace itself with another process, but it must do so via `exec` so that `supervisord` can still monitor it.

The `pidproxy` program may help with some programs that can't work like described above.  If `pidproxy` doesn't meet your needs either, you might be able to write a similar proxy program that does.  However, these are workarounds, and there might be a better solution than `supervisord` for your application.

**Comment by orenmazor** [comment]
@ajpen that's just adding another level of abstraction. Ended up switching to runit where I can do this out of the box :+1:

**Comment by ajpen** [comment]
@orenmazor [unicornherder](https://github.com/gds-operations/unicornherder) would've solved your problem if you wish not to write your own pidproxy. [Source](https://github.com/Supervisor/supervisor/issues/166#issuecomment-59255805)
