### ISSUE TITLE
restart supervisor do not restart subprocess.

### ISSUE THREAD

**Issue by roaporl** [Supervisor/supervisor#892]
I set "stopsignal=QUIT", expecting do not stop subprocesses where supervisord stoped.

but when I start supervisord server, it still try start subprocesses, can not detect the subprocesses are alive.
they are out of control ? 

I just want if the supervisor fail and down, do not affect the subprocesses. When it starts, it still can manage the subprocesses gracefully.
How should I handle this case ?

**Comment by mnaberez** [comment]
Please ask questions about using or installing Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list. We use this issue tracker mainly for bugs in Supervisor itself.

> I just want if the supervisor fail and down, do not affect the subprocesses. When it starts, it still can manage the subprocesses gracefully.
How should I handle this case ?

You can't.  You need to use another program instead of `supervisord`.  The core design of `supervisord` is that is spawns children via fork/exec and then monitors those children with pipes and SIGCHLD.  `supervisord` doesn't have any mechanism that would allow it to attach to processes that are already running, and it likely never will.  `supervisord` always shuts down its children before it exits.  That's the design of the program.

There is a program called `pidproxy` included with Supervisor that will allow `supervisord` to monitor a PID via a pidfile, but this is a workaround, and you won't get stdout/stderr logging like with a program that runs as a child of `supervisord`.
