### ISSUE TITLE
Add an option to require program sections to specify a non-root user

### ISSUE THREAD

**Issue by groutr** [Supervisor/supervisor#898]
We are looking at supervisord to manage many user-level services in an enterprise setting.  Running supervisord as root is attractive, but we need to be able to guarantee every process supervisor executes drops root privileges.

AFAIK, supervisord doesn't make any such guarantee.  We're interested in adding an option to supervisord (like `--no_root_processes` or similar) that will function in one of the following two ways:
1. enforce each `[program:x]` in supervisor.conf (especially any included files) to have a user key defined and it cannot be root.
2. for each file that is included, override/set the uid of each `[program:x]` section to the owner of the included file.

If this is already possible, I'd love learn about how configure supervisor this way.  Otherwise, I'm willing to make the changes in a PR, but I think I might need a little guidance understanding the internals of supervisor.

**Comment by mnaberez** [comment]
> We are looking at supervisord to manage many user-level services in an enterprise setting. Running supervisord as root is attractive, but we need to be able to guarantee every process supervisor executes drops root privileges.

Run supervisord itself as non-root or choose another program instead of Supervisor to enforce enterprise security.  Supervisor just wasn't designed for enforcement of enterprise security as its main function and as such it isn't as paranoid as other programs such as daemontools.  While I'm not aware of an particular vulnerabilities in Supervisor at this time, I don't think Supervisor is a suitable tool for your application.  It was just never designed for the use case you are describing.  I'm not keen on adding config file options that might appear like it was.  Use a different program that was designed from the ground up to enforce enterprise security.

**Comment by groutr** [comment]
This is unfortunate.  Supervisor was the most appealing option.

Perhaps enforce was an incorrectly chosen word.  The two approaches explained above are really more of a validation of the configuration.

**Comment by mnaberez** [comment]
> I'm not trying to say that supervisor be responsible for implementing/enforcing enterprise-grade security.

OK.  Be aware of that supervisord switches the user by calling `setuid()` only, so it doesn't know about PAM.  For example, it is possible that after supervisord drops privileges, that user ends up with higher resource limits than it would have otherwise, because it inherits the limits from supervisord.  So if you're security conscious, I maintain you should run supervisord as non-root or look for another option.

> AFAIK, supervisord doesn't make any such guarantee. We're interested in adding an option to supervisord (like --no_root_processes or similar) that will function in one of the following two ways:
>
>  1.  enforce each [program:x] in supervisor.conf (especially any included files) to have a user key defined and it cannot be root.

There was [an issue](https://github.com/Supervisor/supervisor/blob/3.3.1/CHANGES.txt#L237-L246) a few years ago where I changed how `user=` in a `[program:x]` section is handled both during config reading and process spawning.  Since then, the specified user has to exist on the system at the time the config file is loaded.  Additionally, `supervisord` will refuse to spawn the child if it can't switch to the specified user first.

Since that is in place, I believe that your suggestion could be implemented in `options.py` just by checking that `user=` is set in the program section that name doesn't resolve to uid 0.

> 2. for each file that is included, override/set the uid of each [program:x] section to the owner of the included file.

I'd rather reject it than override it.  Existing config file validations in `options.py` raise `ValueError` when they see something they don't like.  On startup, this causes `supervisord` to refuse to start (with an error in its log).  For config reloading, `supervisord` keeps running but it refuses to reload the config.

**Comment by groutr** [comment]
@mnaberez Thank you for reopening the issue.

> OK. Be aware of that supervisord switches the user by calling setuid() only, so it doesn't know about PAM. For example, it is possible that after supervisord drops privileges, that user ends up with higher resource limits than it would have otherwise, because it inherits the limits from supervisord. So if you're security conscious, I maintain you should run supervisord as non-root or look for another option.

That is very good to know.  Thanks for sharing this information.

> I'd rather reject it than override it. Existing config file validations in options.py raise ValueError when they see something they don't like. On startup, this causes supervisord to refuse to start (with an error in its log). For config reloading, supervisord keeps running but it refuses to reload the config.

I like this suggestion better.

**Comment by timsnyder** [comment]
@mnaberez thanks for pointing out the limitations of `setuid()` vs pam_limits.  @groutr our primary concern is identity and setuid() is sufficient for our purposes.  We can talk about the resources issue in more detail on Monday.

I also would rather that `supervisord` reject `[program:x]` sections without a `user=` key than override them to match the config file's uid.

@mnaberez what do you think about the option to require the `user` key coming from the cmdline versus being set in the config file?  I like having it be cmdline-only because it removes concerns about possibilities for resetting it in the config file.

**Comment by groutr** [comment]
@timsnyder it appears that all options that can be passed on the commandline to supervisord can be set in the config file (in the supervisord section).  Having an option only on the commandline I think might run counter to the way options are designed in supervisor.

**Comment by mnaberez** [comment]
> @groutr our primary concern is identity 

The proposal here does almost nothing to help with identify.  It would only validate that the program is not running as the root user.  Included config files were mentioned above.  If your motivation is to allow non-root users to edit included config files, while access to the root config file is protected by file permissions, it won't work for identity:  Any non-root user can put another non-root user in their config file.

After thinking about this for another couple of days, I've reverted back to my original position that this feature isn't a good fit for supervisord.  It solves only a very limited use case, and other users haven't expressed a need for this use case.  It pretends to add some security, but doesn't really.  I'd rather leave this out entirely, sorry.  There is almost certainly a better tool for your particular application than supervisord.
