### ISSUE TITLE
How does stdout_logfile_backups option work?

### ISSUE THREAD

**Issue by weishen** [Supervisor/supervisor#900]
I am using supervisord to collect logs and I configured

[program:worker]
command = XXX
numprocs = 5
numprocs_start = 1
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile = /opt/logs/worker_supervisord.log
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups = 10

 I thought it worked well, because there are expected 10 log files, e.g. supervisord.log.1 , supervisord.log.2, supervisord.3 etc.
But when I looked into these logs, I found it was not working the way as I thought. The log for 2017-03-06 appears in all supervisord.log ,  supervisord.log.1, supervisord.log.2, supervisord.log.3 supervisord.log.4 files.  Can anyone explain this? or is it a bug?

**Comment by mnaberez** [comment]
> stdout_logfile_maxbytes = 50MB

Rotation will occur whenever the file reaches about 50 megabytes.  It doesn't rotate based on date, it rotates based on file size. 

More about logfile options can be found in the [online manual](http://supervisord.org/configuration.html).  Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by weishen** [comment]
Thanks for replying to me. Maybe I didn't describe it clearly. The fact is supervisord.log has log from 2017-02-16 to 2017-03-06, supervisord.log.1 has log from 2017-02-16 to 2017-03-06, and  supervisord.log.2 , supervisord.log.3 have the same range.  One day's log will not reach to 50MB, it seems like supversior rotated as a mess.  The supervisor version I used is 3.0b2.

**Comment by mnaberez** [comment]
Supervisor [3.0b2](https://github.com/Supervisor/supervisor/blob/3.3.1/CHANGES.txt#L237) is several years old so I tested this on Supervisor [3.3.1](https://github.com/Supervisor/supervisor/blob/3.3.1/CHANGES.txt#L1) instead.  Here is what I tried to duplicate your report.

Python script `letters.py` to print 1 megabyte of each letter `a`, `b`, `c`:
```
import sys
for letter in ('a', 'b', 'c'):
  sys.stdout.write(letter * 1048576)
  sys.stdout.flush()
```

Minimal `supervisord.conf` to run it with log rotation of 1 megabyte:
```
[supervisord]
logfile = /tmp/supervisord.log
loglevel = debug

[program:letters]
command = python /path/to/letters.py
startsecs = 0
autorestart = false
stdout_logfile = /path/to/letters.log
stdout_logfile_maxbytes = 1MB
stdout_logfile_backups = 2
```

Run `supervisord` in the foreground with that config:
```
$ supervisord -n -c /path/to/supervisord.conf
```

The result is three log files:

 - `letters.log`, size 0 (no new data since last rotation)
 - `letters.log.1`, size 1048576, contains only `c`
 - `letters.log.2`, size 1048576, contains only `b`

The above result is as expected.  Since I can't duplicate this report, I am going to leave the issue closed.  If you can provide reproduce instructions similar to the above that shows a bug in a modern version of Supervisor, we can reopen.
