### ISSUE TITLE
Are there any instructions for contributing?

### ISSUE THREAD

**Issue by artburkart** [Supervisor/supervisor#905]
Hi, I wanted to explore the code and tweak it to see if a thing I consider to be a bug could be removed, but it's not clear how one tests supervisor in a dev environment. I contacted the supervisor user list, but received no responses there. Maybe it's dead?

Anyway, here's what I've tried:

```
cd supervisor
git checkout 3.1-branch
virtualenv env
. env/bin/activate
python setup.py develop
cp supervisor/skel/sample.conf supervisor.conf
python supervisor/supervisord.py -c supervisor.conf
sudo python supervisor/supervisorctl.py update
```

But I get this error:

```
Traceback (most recent call last):
  File "supervisor/supervisorctl.py", line 34, in <module>
    from supervisor.medusa import asyncore_25 as asyncore
ImportError: No module named supervisor.medusa
```

**Comment by mnaberez** [comment]
It should be the same as most Python packages.  I usually do something along these lines:

```
$ virtualenv --no-site-packages ~/venv
$ cd ~/supervisor-checkout
$ ~/venv/bin/python setup.py develop
$ ~/venv/bin/supervisord -n -c ~/supervisord.conf
$ ~/bin/supervisorctl -c ~/supervisord.conf
```

I don't know why you get the `ImportError` for `supervisor.medusa`, since it's present in the [source code](https://github.com/Supervisor/supervisor/tree/fa7e3f56c8e4fd1e6e19070a0bcffc0bf5ab3192/supervisor).  Other people have been developing locally and submitting patches, and it works on [Travis CI](https://travis-ci.org/Supervisor/supervisor/builds/208752934) also.  Based on this, I guess something is wrong with your system or the commands you are using.  Maybe it's something to do with the `activate` magic, or the mix or `sudo` and not, or maybe something is broken in your Python installation(s).  I'm afraid I don't know and I can't help troubleshoot it further, sorry.

**Comment by artburkart** [comment]
Thank you for the quick response,

Using your instructions and the `activate` magic worked great. The way I was doing it consistently doesn't work, but it's how I approach most python projects I work on, so that's interesting. Thanks for pointing me to the Travis build. I hadn't considered looking at it. That's a trick I'll use when I tackle projects in the future. :)

I think you're right about the mix of `sudo` and not. The only reason I used `sudo` was because I couldn't get it to run at all otherwise. Regardless, I can now figure out if the thing I'm experiencing is a bug or not, so thank you.
