### ISSUE TITLE
Specifying a non existent log file directory for a single program stops all program from starting

### ISSUE THREAD

**Issue by luto** [Supervisor/supervisor#918]
If one program specifies a log file within a directory, which does _not_ exist, supervisor does not start at all.

```ini
[program:cat]
command=/bin/cat2
stopasgroup=true
redirect_stderr=true
stdout_logfile=/logs2/cat.log
```

Generates the following output:

```
Error: The directory named as part of the path /logs2/cat.log does not exist. in section 'program:cat' (file: 'xxx/cat.ini')
```

This means that a single faulty log config can stop all programs from working, even though their config is perfectly valid.

1. Is this something you'd like to change?
2. Solution A: print a CRIT message on startup, do not load the service at all.
3. Solution B: print a CRIT message on startup, load the service, but replace the broken logfile by `NONE`.

Which of those do you prefer? I'm happy to prepare a PR :)

**Comment by mnaberez** [comment]
`supervisord` performs various checks that its configuration is valid on startup, and intentionally refuses to start if any of its configuration is found to be invalid.  This is by design and won't be changed.  Please fix your configuration as described in the error message and try to start `supervisord` again.

**Comment by luto** [comment]
is there a command to check a given config file for correctness, without actually (re-)starting `supervisord`?
