### ISSUE TITLE
Exception over and over again

### ISSUE THREAD

**Issue by okmkey45** [Supervisor/supervisor#957]
Hello.

I work with laravel framework and I use supervisor for queues processing. 

A few months ago, I was getting a PDOException eveytime the supervisor tried to query my jobs table to check if any task needed to be processed. I did something about this, dirty solution but it worked.

A few days ago, (other app), that also uses the queues, supervisor and database driver, was having trouble. I was getting some deadlock exception for the way that laravel works with queues.

In both cases, when an exception ocurres, it is like the supervisor entries in some state of "numbness" and it gets the same error over and over again.

Now, this is the weird thing. Both cases were solved just by restarting the supervisor. In my first case (PDOException), I check when a PDOException ocurres and then I restart the supervisor. In the second case I restarted manually the supervisor from the terminal and it started to work fine again.

Why do the problems go away just by restarting the supervisor? could it be some settings of laravel?

Hope somebody can help me. Thanks.

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for issues in Supervisor itself.

It is unlikely that we'll be able to help with this particular issue.  `supervisord` doesn't have a way to cause a `PDOException`.  It just launches programs with fork/exec, and then those programs do whatever they do.  If the issue goes away after restarting `supervisord`, that's likely because restarting `supervisord` also restarts all the programs running under it.
