### ISSUE TITLE
supervisord not spawning all processes

### ISSUE THREAD

**Issue by boogybren** [Supervisor/supervisor#997]
When using the package install in Ubuntu (which installs v3.2.0) and using systemctl to start supervisor, the max amount of processes I can run is 342 despite having a total of 1111 in my configs set to spawn.  In the logs, the error:

`spawnerr: too many open files to spawn 'nameofconffile'`

...pops up despite a high ulimit on the server.

After reading stackoverflow complaints, they reported that it was an issue with the version.  So I used easy_install to install v3.3.3.  Because it is not under systemctl control, manually starting it allows me to spawn all the processes that I prescribe.  However I still wanted systemctl to control the daemon.  So I did a cheat and linked the supervisor files in /usr/bin/ to the new version in /usr/local/bin.  Supervisor starts fine using systemctl in this fashion, however it reverts back to the original problem.

We have to manually start it in order to over come this problem.

**Comment by mnaberez** [comment]
> `spawnerr: too many open files to spawn 'nameofconffile'`

This error is [printed](https://github.com/Supervisor/supervisor/blob/3.3.3/supervisor/process.py#L220-L224) when the operating system returns `EMFILE` (too many open files).  There isn't anything we can do in `supervisord` itself to fix this.

> After reading stackoverflow complaints, they reported that it was an issue with the version. So I used easy_install to install v3.3.3. Because it is not under systemctl control, manually starting it allows me to spawn all the processes that I prescribe.

I don't think there is anything we can change in `supervisord` to affect this.  Since you say you are able to run `supervisord` successfully from a shell but not under `systemd`, that suggests an issue with the `systemd` configuration.

You may be able to get help with this issue on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users) (assuming there are `systemd` users there) or on a `systemd` users forum.  Another option might be to run the processes under `systemd` directly without `supervisord`.
